import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {ROBOTS,BUILDINGS} from '../src/foundry/catalog.js';
const root=new URL('../public/models/foundry-01/',import.meta.url),manifest=JSON.parse(readFileSync(new URL('manifest.json',root)));
function glb(file){const bytes=readFileSync(file);assert.equal(bytes.toString('ascii',0,4),'glTF');assert.equal(bytes.readUInt32LE(4),2);assert.equal(bytes.readUInt32LE(8),bytes.length);return {bytes,json:JSON.parse(bytes.toString('utf8',20,20+bytes.readUInt32LE(12)))};}
test('all ten Foundry models are valid self-contained GLBs matching their manifest',()=>{assert.equal(Object.keys(manifest.models).length,10);for(const [type,m] of Object.entries(manifest.models)){const {bytes,json}=glb(new URL(m.file,root));assert.equal(createHash('sha256').update(bytes).digest('hex'),m.sha256);assert.equal(bytes.length,m.bytes);assert.ok(m.triangles>1000&&m.triangles<60000,type);assert.ok(json.meshes.length>0);assert.ok(json.animations.length>0);assert.ok(json.buffers.every(b=>!b.uri));assert.ok(!json.images?.length);for(const accessor of json.accessors)for(const field of ['min','max'])if(accessor[field])assert.ok(accessor[field].every(Number.isFinite));assert.ok(existsSync(new URL('../public/images/foundry/'+type+'.webp',import.meta.url)));}});
test('crew have separate travel and sensor clips and builders have independent work clips',()=>{for(const [role,r] of Object.entries(ROBOTS)){const {json}=glb(new URL(r.asset+'.glb',root)),names=json.animations.map(a=>a.name);assert.ok(names.includes('Travel'),role);assert.ok(names.includes('Idle'),role);if(role!=='hauler')assert.ok(names.includes('Work'),role);assert.ok(r.radius>0&&r.capacity>0&&r.assembly>0);}});
test('new building models have catalog definitions and available source',()=>{for(const type of ['depot','workshop','robotfactory','relay','tunnel','radiator'])assert.ok(BUILDINGS[type]&&manifest.models[type]);assert.ok(existsSync(new URL('../art/blender/build_foundry_assets.py',import.meta.url)));assert.ok(existsSync(new URL('../art/blender/moon-foundry-collection.blend',import.meta.url)));});

test('logistics models have valid embedded geometry and a movable elevator platform',()=>{const root=new URL('../public/models/logistics-01/',import.meta.url),manifest=JSON.parse(readFileSync(new URL('manifest.json',root)));for(const [type,m] of Object.entries(manifest.models)){const {bytes,json}=glb(new URL(m.file,root));assert.equal(createHash('sha256').update(bytes).digest('hex'),m.sha256);assert.ok(json.buffers.every(b=>!b.uri));assert.ok(json.animations.length);if(type==='lift'){const node=json.nodes.findIndex(n=>n.name==='Lift_platform');assert.ok(node>=0);assert.ok(json.animations.some(a=>a.channels.some(c=>c.target.node===node&&c.target.path==='translation')));}}});
