import {BUILDINGS} from './catalog.js';
import {corridorEstimate} from './corridors.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(n);
export function corridorPlanner(w,c,own,draft={}){
 const locals=w.machines.filter(m=>m.claimId===c.id),bores=locals.filter(m=>m.type==='tunnel'),bore=bores.find(m=>String(m.id)===draft.machineId)||bores[0],from=locals.find(m=>String(m.id)===draft.fromId)||locals.find(m=>m.type==='seed');
 const choices=from?w.machines.filter(t=>t.id!==from.id&&corridorEstimate(from,t).valid):[],target=choices.find(t=>String(t.id)===draft.toId),estimate=target&&corridorEstimate(from,target),busy=bore&&w.corridors.some(t=>(t.boreId??t.fromId)===bore.id&&!t.complete);
 const name=m=>esc(BUILDINGS[m.type].name)+' #'+m.id;
 return `<section class="colony-box" id="tunnel-planner"><h3>Plan a tunnel</h3><p>The bore provides the drilling equipment and consumes the liners. Start and End choose the route independently.</p>${bores.length?`<form id="tunnel-plan" data-bore-form><label>Bore doing the work<select name="machineId" ${own?'':'disabled'}>${bores.map(m=>`<option value="${m.id}" ${m===bore?'selected':''}>${name(m)}</option>`).join('')}</select></label><div class="foundry-form-row"><label>Start<select name="fromId" ${own?'':'disabled'}>${locals.map(m=>`<option value="${m.id}" ${m===from?'selected':''}>${name(m)}</option>`).join('')}</select></label><label>End<select name="toId" ${own?'':'disabled'}><option value="">Choose a facility or neighbor’s seed</option>${choices.map(t=>`<option value="${t.id}" ${t===target?'selected':''}>${name(t)}${t.claimId!==c.id?' · '+esc(w.players.find(p=>p.id===t.ownerId)?.name):''} · ${num(corridorEstimate(from,t).length)} m</option>`).join('')}</select></label></div>${estimate?`<p class="corridor-estimate">${num(estimate.metal)} metal + ${num(estimate.parts)} parts over ${num(estimate.length)} m. At least ${num(estimate.poweredSeconds/60)} powered minutes; supply, attention and maintenance can extend this.</p>`:''}<p><small>Local facilities: up to 500 m. Neighboring seeds: up to 6 km. Completed lanes carry robots both ways. Cargo still travels on robots; supplies and power remain separately owned.</small></p><button type="submit" ${own&&!busy&&target?'':'disabled'}>${busy?'Bore is excavating':'Start excavation'}</button></form>`:'<p>Build a bore after researching Below the surface, then plan its route here.</p>'}</section>`;
}
export function corridorLedger(w,c){
 const routes=w.corridors.filter(t=>t.claimId===c.id||t.targetClaimId===c.id);
 return `<section class="colony-box"><h3>Tunnel network · ${routes.length}</h3>${routes.map(t=>{
  const to=w.machines.find(m=>m.id===t.toId),remaining=Math.max(0,t.length-t.excavated),traffic=w.robots.filter(r=>r.tunnelRide?.corridorId===t.id).length;
  return `<article class="foundry-row"><div><strong>${esc(BUILDINGS[w.machines.find(m=>m.id===t.fromId)?.type]?.name||'Start')} #${t.fromId} → ${esc(to?BUILDINGS[to.type].name:'endpoint')} #${t.toId}</strong><p>${t.complete?(t.transport?'Open · two freight lanes':'Connected · legacy utility corridor'):`Excavating ${num(t.excavated)} / ${num(t.length)} m`}${t.transport?' · '+traffic+' robots on route':''}</p><progress value="${t.excavated}" max="${t.length}"></progress>${remaining?`<small>Remaining liners: ${num(remaining*.5)} metal + ${num(remaining*.1)} parts. Watch the bore’s operating status for supply, power or mind limits.</small>`:''}</div><button data-action="focus" data-id="${t.boreId??t.fromId}">Locate bore ↗</button></article>`;
 }).join('')||'<p>Select an installed bore’s endpoint below to connect facilities or reach a neighboring seed.</p>'}</section>`;
}
